version: '3.4'

services:
    catalogdb:
        image: mongo
    basketdb:
        image: redis
    orderdb:
        image: mcr.microsoft.com/mssql/server
    rabbitmq:
        image: rabbitmq:3-management-alpine

    catalogapi:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: src/Catalog/CatalogAPI/Dockerfile
    basketapi:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: src/Basket/BasketAPI/Dockerfile


    orderingapi:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
            context: .
            dockerfile: src/Ordering/OrderingAPI/Dockerfile


    ocelotapigateway:
        image: ${DOCKER_REGISTRY-}ocelotapigateway
        build:
          context: .
          dockerfile: src/ApiGateway/OcelotAPIGateway/Dockerfile

